var menu=
'<h4><a href="index.html"> Из переписки в форумах</a></h4>\
  <p><a href="future.html"> Будущее искусств.разума</a></p>\
  <p><a href="ai.html"> Искусственное сознание</a></p>\
  <p><a href="brain.html"> Возможности мозга</a></p>\
  <p><a href="copying.html"> Копирование сознания</a></p>\
  <p><a href="definition.html"> Что такое сознание</a></p>\
  <p><a href="motor.html"> Ассоциативный мотор</a></p>\
  <p><a href="sense.html"> Формирование смыслов</a></p>\
  <p><a href="will.html"> Механизм свободы воли</a></p>';